### PR TITLE
deleted routes.ts as it is not needed

### PR DESCRIPTION
**Pull request by ChineduOzodi**
Apparently deleting the routes.ts does break something. Need someone to look into this

### CODE REVIEW

**Comment by MarcinSalamon** [comment]
what's the issue with it?

**Comment by ChineduOzodi** [comment]
Steve said to delete it unless there is a reason to have both a route.module.ts and a route.ts. Deleting it causes compilation errors so I'm having @stephenhong look into it.

**Comment by MarcinSalamon** [comment]
```typescript
export const appRoutes: Routes = [
```

needs this class signature on the routes.module I believe

**Comment by ChineduOzodi** [comment]
Needed to delete route.module.ts, not routes.ts

**Pull request closed without merging**
